Dynamic friction
anne-glerum/aspect pull request #5
Opened 2020-06-11 14:40 UTC by EstherHeck

Pull Request Checklist. Please read and check each box with an X. Delete any part not applicable. Ask on the [forum](https://community.geodynamics.org/c/aspect) if you need help with any step.

*Describe what you did in this PR and why you did it.*

### Before your first pull request:

* [ ] I have read the guidelines in our [CONTRIBUTING.md](../blob/master/CONTRIBUTING.md) document.

### For all pull requests:

* [ ] I have followed the [instructions for indenting my code](../blob/master/CONTRIBUTING.md#making-aspect-better).

### For new features/models or changes of existing features:

* [ ] I have tested my new feature locally to ensure it is correct.
* [ ] I have [created a testcase](http://www.math.clemson.edu/~heister/manual.pdf#sec%3Awriting_tests) for the new feature/benchmark in the [tests/](../blob/master/tests/) directory.
* [ ] I have added a changelog entry in the [doc/modules/changes](../blob/master/doc/modules/changes) directory that will inform other users of my change.

2020-06-18 11:39 UTC, anne-glerum requested changes
Hi Esther,
Thanks for putting in the dynamic friction. My comments are mostly about formatting; so to adhere to ASPECT's general style and improve readability. Let me know if anything is unclear.

2020-06-18 11:39 UTC, anne-glerum commented on include/aspect/material_model/visco_plastic.h
> +        * dynamic friction parameters
Please describe shortly what each parameter means and use capitals and punctuation as in the rest of the comments.

2020-06-18 11:39 UTC, anne-glerum commented on source/material_model/visco_plastic.cc
> +          // dynamic angles of internal friction must be converted from degrees into radians. static angles are converted inside drucker_prager
Please use capitals to start your sentences.

2020-06-18 11:39 UTC, anne-glerum commented on source/material_model/visco_plastic.cc
> +          // Then dynamic characterstic strain rate is used to see if dynamic or static angle of internal friction should be used
characterstic -> characteristic

2020-06-18 11:39 UTC, anne-glerum commented on source/material_model/visco_plastic.cc
> +          const double current_friction = dynamic_angles_of_internal_friction[j] *numbers::PI/180.0+ (drucker_prager_parameters.angles_internal_friction[j] * weakening_factors[1] - dynamic_angles_of_
It's nicer if lines fit into the width of the screen of e.g. vi, ~100 characters. Please break up this line into several lines that for example start with the addition/multiplication sign. Also be consistent with spacing, e.g. one space between symbols and variable names.

2020-06-18 11:39 UTC, anne-glerum commented on source/material_model/visco_plastic.cc
> +          const double current_friction = dynamic_angles_of_internal_friction[j] *numbers::PI/180.0+ (drucker_prager_parameters.angles_internal_friction[j] * weakening_factors[1] - dynamic_angles_of_
As internally you usually always want to work with radians (this is what functions like tan and sin expect), it's clearer to convert to radians as soon as you read in the friction angles in the `parse_parameters` function. See the static angles in `rheology/drucker_prager.cc`

2020-06-18 11:39 UTC, anne-glerum commented on source/material_model/visco_plastic.cc
> +              // plastic_out->friction_angles[i] += 180.0/numbers::PI * volume_fractions[j] * (drucker_prager_parameters.angles_internal_friction[j] * weakening_factors[1]);
rm this line

2020-06-18 11:39 UTC, anne-glerum commented on source/material_model/visco_plastic.cc
> +              plastic_out->friction_angles[i] += 180.0/numbers::PI * volume_fractions[j] * (dynamic_angles_of_internal_friction[j] *numbers::PI/180.0+ (drucker_prager_parameters.angles_internal_frict
- please break up this line into several lines
- When you have changed the internal unit of the dynamic angles, you can remove the multiple numbers::PI/180.0 here

2020-06-18 11:39 UTC, anne-glerum commented on source/material_model/visco_plastic.cc
> +                             "between the dynamic and the static angle of friction. When the effective strain rate "
This description sounds like a step-like change from static to dynamic friction angles, but that's not the case right?

2020-06-18 11:39 UTC, anne-glerum commented on source/material_model/visco_plastic.cc
> +                             "surpasses the dynamic characteristic strain rate. "
see above comment

2020-06-18 11:39 UTC, anne-glerum commented on source/material_model/visco_plastic.cc
> +                             "friction is taken, otherwise the static angle of internal friction is chosen."
Add space before last ", otherwise the next line will start directly in the output, instead of after a space.

2020-06-18 11:39 UTC, anne-glerum commented on source/material_model/visco_plastic.cc
> +                             " to equation 13 in van Dinther et al., (2013, JGR). A factor between 0 and 1 makes the "
Please remove the space after the first " and put it before the last " of the previous line.

2020-06-18 11:39 UTC, anne-glerum commented on source/material_model/visco_plastic.cc
> +          dynamic_friction_smoothness_exponent = Utilities::possibly_extend_from_1_to_N (Utilities::string_to_double(Utilities::split_string_list(prm.get("Dynamic friction smoothness exponent"))),
Is it necessary that the smoothness exponent can vary between compositions?

2020-06-18 11:39 UTC, anne-glerum commented on source/material_model/visco_plastic.cc
> +          //Dynamic friction paramters
Space before Dynamic

2020-06-26 14:01 UTC, EstherHeck commented on source/material_model/visco_plastic.cc
> +          dynamic_friction_smoothness_exponent = Utilities::possibly_extend_from_1_to_N (Utilities::string_to_double(Utilities::split_string_list(prm.get("Dynamic friction smoothness exponent"))),
true, but how do I do it?  looking at min_visc I thought this is the way, but it does not compile: 
dynamic_friction_smoothness_exponent = prm.get_double("Dynamic friction smoothness exponent");
This is the start of the error: 
/home/hecken/code/aspect/source/material_model/visco_plastic.cc:939:48: error: no match for ‘operator=’ (operand types are ‘std::vector<double, std::allocator<double> >’ and ‘double’)
           dynamic_friction_smoothness_exponent = prm.get_double("Dynamic friction smoothness exponent");

2020-06-26 14:50 UTC, anne-glerum commented on source/material_model/visco_plastic.cc
> +          dynamic_friction_smoothness_exponent = Utilities::possibly_extend_from_1_to_N (Utilities::string_to_double(Utilities::split_string_list(prm.get("Dynamic friction smoothness exponent"))),
In the header (.h) file, the type of the parameter `dynamic_friction_smoothness_exponent` is set. At the moment, it is a vector of doubles, so you cannot assign a double to the vector as a whole. When you just want one exponent for all fields, you can change the type to `double` and keep the change you suggest (`prm.get_double`).

2020-06-26 14:56 UTC, EstherHeck commented on source/material_model/visco_plastic.cc
> +          dynamic_friction_smoothness_exponent = Utilities::possibly_extend_from_1_to_N (Utilities::string_to_double(Utilities::split_string_list(prm.get("Dynamic friction smoothness exponent"))),
thanks!

2020-10-19 07:34 UTC, closed without merging